/**
 * 门户 / 后台场景精选 lucide 图标清单
 * name 必须是 lucide-vue-next 的 PascalCase 导出名（由 scripts/verify-icon-options.mjs 校验）
 * label 为中文标签，供图标选择器搜索与 tooltip 使用
 */
export interface IconOption {
  name: string
  label: string
}

export const ICON_OPTIONS: IconOption[] = [
  // 知识 / 文档
  { name: 'BookOpen', label: '知识库' },
  { name: 'Book', label: '文档' },
  { name: 'Notebook', label: '笔记' },
  { name: 'FileText', label: '文本文件' },
  { name: 'Files', label: '多文件' },
  { name: 'Folder', label: '文件夹' },
  { name: 'FolderOpen', label: '打开文件夹' },
  { name: 'Bookmark', label: '书签' },
  { name: 'StickyNote', label: '便签' },
  { name: 'Newspaper', label: '新闻' },
  { name: 'ScrollText', label: '合同' },

  // 协作 / 沟通
  { name: 'Users', label: '团队' },
  { name: 'User', label: '用户' },
  { name: 'UserPlus', label: '添加成员' },
  { name: 'UserRound', label: '成员' },
  { name: 'MessageSquare', label: '讨论' },
  { name: 'MessageCircle', label: '聊天' },
  { name: 'MessagesSquare', label: '论坛' },
  { name: 'Mail', label: '邮件' },
  { name: 'Send', label: '发送' },
  { name: 'Phone', label: '电话' },
  { name: 'Video', label: '视频会议' },
  { name: 'Megaphone', label: '公告' },
  { name: 'Bell', label: '通知' },
  { name: 'AtSign', label: '提及' },
  { name: 'Share2', label: '分享' },

  // 日程 / 任务
  { name: 'CalendarDays', label: '日历' },
  { name: 'Calendar', label: '日程' },
  { name: 'CalendarClock', label: '日程提醒' },
  { name: 'Clock', label: '时钟' },
  { name: 'Timer', label: '计时' },
  { name: 'AlarmClock', label: '闹钟' },
  { name: 'Clipboard', label: '剪贴板' },
  { name: 'ClipboardList', label: '清单' },
  { name: 'ClipboardCheck', label: '任务' },
  { name: 'KanbanSquare', label: '看板' },
  { name: 'ListChecks', label: '待办' },
  { name: 'CheckCheck', label: '已完成' },
  { name: 'CircleCheck', label: '通过' },
  { name: 'SquareCheck', label: '勾选' },

  // 数据 / 报表
  { name: 'BarChart3', label: '柱状图' },
  { name: 'BarChart', label: '图表' },
  { name: 'LineChart', label: '折线图' },
  { name: 'PieChart', label: '饼图' },
  { name: 'TrendingUp', label: '增长' },
  { name: 'TrendingDown', label: '下降' },
  { name: 'Activity', label: '动态' },
  { name: 'Gauge', label: '仪表盘' },
  { name: 'Table', label: '数据表' },
  { name: 'Database', label: '数据库' },
  { name: 'Layers', label: '分层' },
  { name: 'Filter', label: '筛选' },

  // 研发 / IT
  { name: 'GitBranch', label: '代码分支' },
  { name: 'GitPullRequest', label: '合并请求' },
  { name: 'Code', label: '代码' },
  { name: 'Terminal', label: '终端' },
  { name: 'Bug', label: '缺陷' },
  { name: 'Server', label: '服务器' },
  { name: 'Cpu', label: '算力' },
  { name: 'Cloud', label: '云' },
  { name: 'CloudUpload', label: '上传' },
  { name: 'CloudDownload', label: '下载' },
  { name: 'HardDrive', label: '存储' },
  { name: 'Network', label: '网络' },
  { name: 'Wifi', label: '无线' },
  { name: 'Wrench', label: '运维' },
  { name: 'Settings', label: '设置' },
  { name: 'Shield', label: '安全' },
  { name: 'ShieldCheck', label: '合规' },
  { name: 'Lock', label: '锁定' },
  { name: 'Key', label: '密钥' },

  // 业务 / 行政
  { name: 'Briefcase', label: '办公' },
  { name: 'Building2', label: '企业' },
  { name: 'Building', label: '楼宇' },
  { name: 'Landmark', label: '机构' },
  { name: 'Calculator', label: '财务' },
  { name: 'CreditCard', label: '支付' },
  { name: 'Wallet', label: '报销' },
  { name: 'Receipt', label: '票据' },
  { name: 'Package', label: '资产' },
  { name: 'Boxes', label: '库存' },
  { name: 'Truck', label: '物流' },
  { name: 'ShoppingCart', label: '采购' },
  { name: 'Tag', label: '标签' },
  { name: 'Gift', label: '福利' },
  { name: 'Award', label: '荣誉' },
  { name: 'GraduationCap', label: '培训' },
  { name: 'Presentation', label: '演示' },
  { name: 'Target', label: '目标' },
  { name: 'Flag', label: '里程碑' },
  { name: 'Lightbulb', label: '创意' },
  { name: 'Rocket', label: '上线' },
  { name: 'Sparkles', label: '智能' },
  { name: 'Workflow', label: '流程' },
  { name: 'Bot', label: '机器人' },
  { name: 'Puzzle', label: '集成' },
  { name: 'Plug', label: '插件' },
  { name: 'Zap', label: '自动化' },

  // 常用导航
  { name: 'Link', label: '链接' },
  { name: 'ExternalLink', label: '外部链接' },
  { name: 'Globe', label: '全球' },
  { name: 'Home', label: '首页' },
  { name: 'LayoutDashboard', label: '工作台' },
  { name: 'LayoutGrid', label: '应用' },
  { name: 'Grid', label: '网格' },
  { name: 'Search', label: '搜索' },
  { name: 'Star', label: '收藏' },
  { name: 'Heart', label: '点赞' },
  { name: 'ThumbsUp', label: '好评' },
  { name: 'Download', label: '下载' },
  { name: 'Upload', label: '上传' },
  { name: 'Printer', label: '打印' },
  { name: 'Paperclip', label: '附件' },
  { name: 'MapPin', label: '位置' },
  { name: 'Compass', label: '探索' },
]
